port: "_env:YESOD_PORT:8080"

database:
  user:     "_env:YESOD_PGUSER:misterio"
  host:     "_env:YESOD_PGHOST:/var/run/postgresql"
  port:     "_env:YESOD_PGPORT:5432"
  password: "_env:YESOD_PASSWORD:abc123"
  database: "_env:YESOD_PGDATABASE:misterio"
  poolsize: "_env:YESOD_PGPOOLSIZE:10"

session:
  timeout: "_env:YESOD_SESSION_TIMEOUT:60"
  file-path: "_env:YESOD_SESSION_KEY_PATH:config/session.aes"
