port: "_env:YESOD_PORT:8080"

database:
  user:     "_env:YESOD_PGUSER:pokedex"
  host:     "_env:YESOD_PGHOST:/var/run/postgresql"
  port:     "_env:YESOD_PGPORT:5432"
  password: "_env:YESOD_PASSWORD:1234"
  database: "_env:YESOD_PGDATABASE:pokedex"
  poolsize: "_env:YESOD_PGPOOLSIZE:10"

session:
  timeout: "_env:YESOD_SESSION_TIMEOUT:60"
  file-path: "_env:YESOD_SESSION_KEY_PATH:session.aes"
